### ISSUE TITLE
Snowball leveling and dig fails with recent minetest_game

### ISSUE THREAD

**Issue by t4im** [Splizard/minetest-mod-snow#7]
Since minetest/minetest_game@4ec4672 (bisected starting from the stable 4.11) leveling of snow fails.
Digging snow is possible but results in stacks of 65k snowballs (probably some level related underflow)

**Comment by Splizard** [comment]
Fixed f99ba3a1f63190a5185eed90de8003af40c98a3e

**Comment by t4im** [comment]
Same issue still exists, just with additional visual glitch. :)
The Leveling is not shown at all anymore and you still get 65k snowballs.

**Comment by Splizard** [comment]
Has leveled support been removed completely?

**Comment by Splizard** [comment]
Nevermind found the issue.

**Comment by Splizard** [comment]
02e64c9d1b168fb1b02b962354e26904ccc9b24c
